version: '3'
services:
  botapi:
    build:
      context: ./bot
    ports:
      - 5090:5090
    networks:
      - my-network
    depends_on:
      - lavalink

  lavalink:
    build:
      context: ./lavalink
    ports:
      - 2333:2333
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - botapi

networks:
  my-network:
