version: '3'
services:
  fastapi:
    build:
      context: ./bot
    ports:
      - 5090:5090
    networks:
      - my-network

  lavalink:
    build:
      context: ./lavalink
    ports:
      - 2333:2333
    networks:
      - my-network

networks:
  my-network:
